#LDFLAGS for loader flags; EXTRA_CFLAGS for file inclusion
#LDADD for linking and loading the library
SRCS=./main.cpp ./evaluation_of_postfix_expression.cpp ./two_stacks_in_one_array.cpp
PROG=stacks
CFLAGS=-g -Wall
CC= g++
include /usr/lib/build/linux.prog.mk
