#LDFLAGS for loader flags; EXTRA_CFLAGS for file inclusion
#LDADD for linking and loading the library
SRCS=./two_stacks_in_one_array.c 
PROG=stacks
CFLAGS=-g -Wall
include /usr/lib/build/linux.prog.mk
