#LDFLAGS for loader flags; EXTRA_CFLAGS for file inclusion
#LDADD for linking and loading the library
SRCS=./even_odd.c 
PROG=threads
CFLAGS=-g -Wall
LDFLAGS=-lpthread
include /usr/lib/build/linux.prog.mk
